name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - gast==0.2.2
  - imageio=2.6
  - ipython=7.12
  - ipywidgets==7.5.1
  - pillow=7.0
  - pip
  - psutil=5.7
  - py-xgboost=0.90
  - pydot=1.4
  - pyopengl=3.1
  - python-graphviz
  - python=3.7
  #- pyvirtualdisplay=0.2 # add if on headless server
  - scikit-image=0.16
  - wheel
  - widgetsnbextension=3.5
  - widgetsnbextension=3.5
  - pip:
    - -r file:requirements.txt
